### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by loretoparisi** [utahiosmac/jobs#1]
Is this library this Swift 3 only?

**Comment by MarkQSchultz** [comment]
Yes, Swift 3 only.

**Comment by loretoparisi** [comment]
@MarkQSchultz ok so only on macOS Beta. Do you have a sample of jobs queueing?
Btw Thank you for this interesting project 💯

**Comment by MarkQSchultz** [comment]
macOS beta, iOS beta, watchOS beta, and tvOS beta can all use it.

**Comment by MarkQSchultz** [comment]
And no, no sample code yet. The project is still in a pretty early stage. Though in theory it's ready for use.

**Comment by loretoparisi** [comment]
@MarkQSchultz ok thank you as soon as I have the beta I will have a look!
